name: MacOS x86_64 release

on:
  release:
    types: [created] 

jobs:
  build:

    runs-on: macos-latest-large

    steps:
    - uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm' # See 'Options' for all available distributions
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: cache ~/.m2
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build native executable
      run: ./mvnw package -Dnative -Dmaven.repo.local=/tmp
    - name: Get version
      shell: bash -l {0}
      run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
    - name: Get artifactId
      shell: bash -l {0}
      run: echo project_artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout) >> $GITHUB_ENV
    - name: Upload native executable
      id: upload-native-executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/${{env.project_artifactId}}-${{env.project_version}}-runner
        asset_name: ${{env.project_artifactId}}-macos-x86_64
        asset_content_type: application/octet-stream